var catch_phrases = [
	'Wow, sarcasm! That\'s <span class="hilight">original</span>!',
	'The status is not <span class="hilight">quo</span>.',
	'It smells like <span class="hilight">cumin</span>.',
	'Underthings <span class="hilight">tumbling</span>.',
	'Just a few weeks away from a real, <span class="hilight">audible</span> connection.',
	'Buy rocket packs and go to the <span class="hilight">moon</span> and become <span class="hilight">florists</span>.',
	'Seems destiny ends with <span class="hilight">me</span> saving <span class="hilight">you</span>.',
	'You don\'t happen to like frozen yogurt, <span class="hilight">do you</span>?',
	'What a crazy random <span class="hilight">happenstance</span>.',
	'Trust your <span class="hilight">instincts</span>.',
	'Is that the new <span class="hilight">catchphrase</span>?',
	'Even in the darkness every <span class="hilight">color</span> can be found.',
	'We\'re meeting now for the <span class="hilight">first</span> time.',
	'We do the <span class="hilight">weird</span> stuff.',
	'Your real home is in your <span class="hilight">chest</span>.',
	'Someone <span class="hilight">maternal</span>!',
	'Percy is not self-aware. <span class="hilight">Yet</span>.',
	'Percy always knows where his <span class="hilight">towel</span> is.',
	'This site is a <span class="hilight">creeper</span> free zone. You are welcome.',
	'Yeah, I can do <span class="hilight">that</span>.',
	'It\'s kinda <span class="hilight">fun</span> to do the <span class="hilight">impossible</span>.',
	'My work is a <span class="hilight">game</span> -- a very <span class="hilight">serious</span> game.',
	'Attempt the <span class="hilight">impossible</span> in order to <span class="hilight">improve</span> your work.',
	'Sometimes you gotta <span class="hilight">create</span> what you want to be a part of.',
	'If you\'re <span class="hilight">strong</span> enough, there are no precedents.',
	'Policy is a <span class="hilight">guide</span> to the wise and a <span class="hilight">rule</span> to the fool.',
	'Sleep is just a <span class="hilight">bad</span> habit.',
	'Technology <span class="hilight">storyboard.</span>',
	'Supplying your <span class="hilight">fix</span>... of technology.',
	'<span class="hilight">Hooked</span> on ARGs!',
	'Made with <span class="hilight">pixels</span>.',
	'These are <span class="hilight">random</span>. <span class="hilight">Nobody</span> notices at first.',
	'Let\'s have some <span class="hilight">new</span> clich&eacute;s.',
	'Metadata is <span class="hilight">always</span> true!',
	'We never really <span class="hilight">grow up</span>, we only learn how to act in <span class="hilight">public</span>.',
	'When in doubt, <span class="hilight">mumble</span>.',
	'I intend to live <span class="hilight">forever</span>. So far, <span class="hilight">so good</span>.',
	'With sufficient <span class="hilight">thrust</span>, pigs fly <span class="hilight">just fine</span>.',
	'<span class="hilight">Trouble</span> is only an <span class="hilight">opportunity</span> in work clothes.',
	'<span class="hilight">Efficiency</span> is <span class="hilight">intelligent</span> laziness.',
	'Everything should be made as simple as <span class="hilight">possible</span>, but not <span class="hilight">simpler</span>.',
	'Well <span class="hilight">done</span> is better than well <span class="hilight">said</span>.',
	'The best way to <span class="hilight">predict</span> the future is to <span class="hilight">invent</span> it.',
	'<span class="hilight">Consistency</span> is the final refuge of the <span class="hilight">unimaginative</span>.',
	'Work is only <span class="hilight">work</span> if you\'d rather be doing <span class="hilight">something else</span>.',
	'If <span class="hilight">life</span> does not offer a game worth playing, invent a <span class="hilight">new</span> one.',
	'The <span class="hilight">truth</span> is out there.',
	'<span class="hilight">Research</span> is what I\'m doing when I <span class="hilight">don\'t know</span> what I\'m doing.',
	'<span class="hilight">Imagination</span> is more important than <span class="hilight">knowledge</span>.',
	'Logic is a system whereby one may go <span class="hilight">wrong</span> with confidence.',
	'A ship doesn\'t travel far in a <span class="hilight">calm</span> sea.',
	'Opportunities multiply as they are <span class="hilight">seized</span>.',
	'What a <span class="hilight">strange</span> game. The <span class="hilight">only</span> winning move is not to play.',
	'Don\'t <span class="hilight">fear</span> change -- <span class="hilight">embrace</span> it.',
	'An <span class="hilight">error</span> is not a <span class="hilight">mistake</span> until you refuse to correct it.',
	'Don\'t let <span class="hilight">fear</span> stop you.',
	'No <span class="hilight">pressure</span>, no <span class="hilight">diamonds</span>.',
	'Kites rise highest <span class="hilight">against</span> the wind, not with it.',
	'You don\'t drown by <span class="hilight">falling</span> in the water, you drown by <span class="hilight">staying</span> there.',
	'Success is the sum of <span class="hilight">small</span> efforts, <span class="hilight">repeated</span> day in and day out.',
	'He who hesitates is probably <span class="hilight">smart</span>... or <span class="hilight">stapled</span> to the floor.',
	'Hitch your wagon to a <span class="hilight">star</span>.',
	'Nothing <span class="hilight">great</span> was ever achieved without <span class="hilight">enthusiasm</span>.',
	'<span class="hilight">Failure</span> is the opportunity to <span class="hilight">begin again</span> more intelligently.',
	'You can\'t cross a chasm in two <span class="hilight">small</span> jumps.',
	'The <span class="hilight">harder</span> you fall, the <span class="hilight">higher</span> you bounce.',
	'Life is a great big <span class="hilight">canvas</span>. Throw all the <span class="hilight">paint</span> you can at it.',
	'Pick battles big enough to <span class="hilight">matter</span>, but small enough to <span class="hilight">win</span>.',
	'All the world\'s a <span class="hilight">stage</span> and most of us are desperately <span class="hilight">unrehearsed</span>.',
	'Why not go out on a <span class="hilight">limb</span>? That\'s where all the <span class="hilight">fruit</span> is!',
	'Anyone can hold the helm when the seas are <span class="hilight">calm</span>.',
	'After all is said and done, a lot more is usually <span class="hilight">said</span> than <span class="hilight">done</span>.',
	'Inside every <span class="hilight">large</span> problem is a <span class="hilight">small</span> problem struggling to get out.',
	'Watch for big <span class="hilight">problems</span>; they disguise big <span class="hilight">opportunities</span>.',
	'If all the world is a <span class="hilight">stage</span>, where is the <span class="hilight">audience</span> sitting?',
	'It\'s better than <span class="hilight">bad</span>, it\'s <span class="hilight">good</span>.'
];
catch_phrases[catch_phrases.length] = 'There are <span class="hilight">' + catch_phrases.length + '</span> random phrases.';

exports.getQuip = function() {
	var rnd = Math.floor(Math.random() * catch_phrases.length);
	console.log(rnd);
	return catch_phrases[rnd];
}